package com.github.maskedkunisquat.musicmanager.logic.sim

import com.github.maskedkunisquat.musicmanager.logic.event.SimEvent
import com.github.maskedkunisquat.musicmanager.logic.model.ArtistState
import com.github.maskedkunisquat.musicmanager.logic.model.CapabilityType
import com.github.maskedkunisquat.musicmanager.logic.model.LabelNeedType
import com.github.maskedkunisquat.musicmanager.logic.model.MarketState
import com.github.maskedkunisquat.musicmanager.logic.model.NeedType
import com.github.maskedkunisquat.musicmanager.logic.model.ReputationCommunity
import com.github.maskedkunisquat.musicmanager.logic.model.SimWorld
import kotlin.math.abs
import kotlin.random.Random

private const val NEED_URGENT_THRESHOLD = 0.3f
private const val CONTRACT_EXPIRY_WARNING_DAYS = 30
private const val MARKET_SHIFT_THRESHOLD = 0.08f
private const val INTEL_BASE_CHANCE = 0.25f
// Probability that an IntelDrop targets a roster genre (vs. a random market genre).
private const val INTEL_ROSTER_GENRE_WEIGHT = 0.70f
// Re-offer a deferred capability after this many ticks (~2.2 real days).
private const val CAPABILITY_NOTICE_COOLDOWN = 20
// Suppress repeated label-need warnings for this many ticks (~27 real hours).
private const val LABEL_NEED_COOLDOWN = 10
// Minimum ticks before the same want re-surfaces for the same artist.
private const val WANT_RESURFACE_COOLDOWN = 5
// Tape deck: how often leads surface, cap of concurrent visible leads.
private const val LEAD_SURFACE_INTERVAL = 3
private const val LEAD_SURFACE_CAP = 3
private const val PASS_LEAD_COOLDOWN = 10
private const val WATCH_LEAD_RESURFACE_COOLDOWN = 5

private val LABEL_NEED_THRESHOLDS = mapOf(
    LabelNeedType.CASH_FLOW      to 0.35f,
    LabelNeedType.GENRE_DIVERSITY to 0.40f
)

// Costs in cents; gates are (reputation community threshold, funds threshold).
private data class CapabilitySpec(
    val cost: Long,
    val repGate: Pair<ReputationCommunity, Float>? = null,
    val fundsGate: Long? = null
)

private val CAPABILITY_SPECS = mapOf(
    CapabilityType.PUBLICIST       to CapabilitySpec(cost = 1_500_000L, repGate = ReputationCommunity.PRESS to 0.4f),
    CapabilityType.IN_HOUSE_BOOKING to CapabilitySpec(cost = 2_000_000L, repGate = ReputationCommunity.VENUE_BOOKERS to 0.4f),
    CapabilityType.VIDEO_PRODUCTION to CapabilitySpec(cost = 2_500_000L, fundsGate = 5_000_000L)
)

// previousMarket: world before tickMarket ran this tick — used to detect meaningful shifts.
// rng: seeded by SimEngine from world.seed; default fixed seed keeps tests deterministic.
internal fun generateEvents(
    world: SimWorld,
    previousMarket: MarketState = world.market,
    rng: Random = Random(0L)
): List<SimEvent> = buildList {
    for (artist in world.artists.values) {
        addAll(needEvents(artist, world.currentDay))
        addAll(contractEvents(artist, world))
        addAll(wantEvents(artist, world.currentDay))
    }
    addAll(marketShiftEvents(world, previousMarket))
    addAll(intelDropEvents(world, rng))
    addAll(labelNeedEvents(world))
    addAll(capabilityUnlockableEvents(world))
    addAll(leadSurfacedEvents(world))
    // ScoutReport events are generated by ScoutTicker.tickScouts() in SimEngine.tick()
    // and concatenated after this list — they need to mutate scout.lastReportDay in world state.
}

private fun needEvents(artist: ArtistState, day: Int): List<SimEvent> =
    artist.needs.values
        .filter { it.value < NEED_URGENT_THRESHOLD }
        .map { need ->
            SimEvent.NeedUrgent(
                artistId = artist.id,
                needType = need.type,
                currentValue = need.value,
                dayOfGame = day
            )
        }

private fun contractEvents(artist: ArtistState, world: SimWorld): List<SimEvent> {
    val contractId = artist.contractId ?: return emptyList()
    val contract = world.contracts[contractId] ?: return emptyList()
    val daysRemaining = contract.expiryDay - world.currentDay
    if (daysRemaining !in 1..CONTRACT_EXPIRY_WARNING_DAYS) return emptyList()
    return listOf(
        SimEvent.ContractExpiring(
            artistId = artist.id,
            contractId = contractId,
            daysRemaining = daysRemaining,
            dayOfGame = world.currentDay
        )
    )
}

private fun wantEvents(artist: ArtistState, day: Int): List<SimEvent> =
    artist.activeWants
        .filter { it.urgency >= 0.7f }
        .filter { want ->
            val lastSurfaced = artist.wantLastSurfacedAt[want.type.name]
            lastSurfaced == null || day - lastSurfaced >= WANT_RESURFACE_COOLDOWN
        }
        .map { want ->
            SimEvent.WantSurfaced(
                artistId = artist.id,
                wantType = want.type,
                urgency = want.urgency,
                dayOfGame = day
            )
        }

private fun marketShiftEvents(world: SimWorld, previousMarket: MarketState): List<SimEvent> =
    world.market.genreTrends.mapNotNull { (genre, currentTrend) ->
        val previousTrend = previousMarket.genreTrends[genre] ?: return@mapNotNull null
        if (abs(currentTrend - previousTrend) >= MARKET_SHIFT_THRESHOLD) {
            SimEvent.MarketShift(
                genre = genre,
                previousTrend = previousTrend,
                currentTrend = currentTrend,
                dayOfGame = world.currentDay
            )
        } else null
    }

private fun intelDropEvents(world: SimWorld, rng: Random): List<SimEvent> {
    if (rng.nextFloat() > INTEL_BASE_CHANCE) return emptyList()
    val rosterGenres = world.artists.values.map { it.genre }.toSet()
    val genrePool = world.market.genreTrends.keys.toList().ifEmpty { return emptyList() }
    // Artists with low RECOGNITION need benefit most from market awareness; their genre gets extra
    // weight in the pool by appearing twice (once from rosterGenres, once from the recognition list).
    val recognitionHungryGenres = world.artists.values
        .filter { (it.needs[NeedType.RECOGNITION]?.value ?: 1f) < NEED_URGENT_THRESHOLD }
        .map { it.genre }
        .filter { it in world.market.genreTrends }
    val weightedRosterPool = rosterGenres.toList() + recognitionHungryGenres
    val genre = if (weightedRosterPool.isNotEmpty() && rng.nextFloat() < INTEL_ROSTER_GENRE_WEIGHT) {
        weightedRosterPool.random(rng)
    } else {
        genrePool.random(rng)
    }
    val trend = world.market.genreTrends[genre] ?: return emptyList()
    return listOf(SimEvent.IntelDrop(genre = genre, headline = stubHeadline(genre, trend), dayOfGame = world.currentDay))
}

private fun capabilityUnlockableEvents(world: SimWorld): List<SimEvent> =
    CAPABILITY_SPECS.mapNotNull { (type, spec) ->
        if (type in world.label.capabilities) return@mapNotNull null
        val lastNoticed = world.capabilityNoticedAt[type.name]
        if (lastNoticed != null && world.currentDay - lastNoticed < CAPABILITY_NOTICE_COOLDOWN) return@mapNotNull null
        val repGateMet = spec.repGate?.let { (community, threshold) ->
            (world.label.reputation[community] ?: 0f) > threshold
        } ?: true
        val fundsGateMet = spec.fundsGate?.let { world.label.funds > it } ?: true
        if (repGateMet && fundsGateMet) {
            SimEvent.CapabilityUnlockable(type, spec.cost, world.currentDay)
        } else null
    }

private fun labelNeedEvents(world: SimWorld): List<SimEvent> {
    val values = LabelNeedEvaluator.evaluate(world)
    return LABEL_NEED_THRESHOLDS.mapNotNull { (needType, threshold) ->
        val value = values[needType] ?: return@mapNotNull null
        if (value >= threshold) return@mapNotNull null
        val lastNoticed = world.labelNeedNoticedAt[needType.name]
        if (lastNoticed != null && world.currentDay - lastNoticed < LABEL_NEED_COOLDOWN) return@mapNotNull null
        SimEvent.LabelNeedUrgent(needType, value, world.currentDay)
    }
}

private fun leadSurfacedEvents(world: SimWorld): List<SimEvent> {
    if (world.currentDay % LEAD_SURFACE_INTERVAL != 0) return emptyList()
    val cap = LEAD_SURFACE_CAP - world.surfacedLeads.size
    if (cap <= 0) return emptyList()
    val day = world.currentDay
    val fromWatch = world.prospects.values.filter { p ->
        p.id in world.watchedLeads &&
        (world.watchedLeads[p.id]?.let { day - it >= WATCH_LEAD_RESURFACE_COOLDOWN } == true) &&
        p.id !in world.surfacedLeads
    }
    val fresh = world.prospects.values.filter { p ->
        p.id !in world.surfacedLeads &&
        p.id !in world.watchedLeads &&
        p.id !in world.activeNegotiations &&
        p.id !in world.unavailableProspects &&
        (world.passedLeads[p.id]?.let { day - it >= PASS_LEAD_COOLDOWN } ?: true)
    }
    return (fromWatch + fresh).take(cap).map { p ->
        SimEvent.LeadSurfaced(prospectId = p.id, dayOfGame = day)
    }
}

// Stub headlines — replaced by AI-generated text in 2-B.
private fun stubHeadline(genre: String, trend: Float): String = when {
    trend > 0.75f -> "$genre is dominating — labels scrambling to sign anything in the space"
    trend > 0.60f -> "$genre momentum building — scouts reporting strong live turnout"
    trend > 0.50f -> "$genre holding steady — cautious optimism from distributors"
    trend > 0.40f -> "$genre losing ground — oversaturation concerns in the trades"
    trend > 0.25f -> "$genre cooling off — a few breakout acts keeping it on life support"
    else          -> "$genre in a rough patch — labels quietly pulling back budgets"
}
