package com.github.maskedkunisquat.musicmanager.logic.inbox

import com.github.maskedkunisquat.musicmanager.logic.response.ResponseOption

data class TapeDeckItem(
    val id: String,             // event log row ID; used to call resolveEvent
    val prospectId: String,
    val dayOfGame: Int,
    val options: List<ResponseOption>  // PURSUE / PASS / WATCH pre-generated by StubAiProvider
)
